### ISSUE TITLE
Skip the "snip" syntax?

### ISSUE THREAD

**Issue by nashrocks13** [puyt/cerebro-snippets#1]
I really like the idea of being able to search through saved snippets from a launcher like this, but having to type "snip" and then the search term every time seems like a waste.

**Would it be possible to configure this plugin so that saved snippets appear in Cerebro alongside other items based on any search** (i.e., "style.css" instead of "snip style.css"), or is the "snip" syntax required by Cerebro (or problematic for other reasons)?

**Comment by puyt** [comment]
@nashrocks13 I'll try and test it this weekend but it's a bit annoying since the master branch of Cerebro is currently broken for a month

**Comment by puyt** [comment]
@nashrocks13 sorry it took me a while to implement this.
I was busy moving to a new house in February/March and totally forgot about it 😅 

Anyway you can now disable the keyword `snip` using the plugin settings. 😄
