### ISSUE TITLE
Would you like to migrate this package into our organization?

### ISSUE THREAD

**Issue by ogustavo-pereira** [puyt/cerebro-snippets#5]
We are centralizing brain plugins within the organization, would you like to move this one?

@puyt

**Comment by puyt** [comment]
@oguhpereira sure

**Comment by ogustavo-pereira** [comment]
great I just sent you the organization invite

**Comment by puyt** [comment]
how would you like to migrate this plugin? Transferring ownership doesn't work

**Comment by ogustavo-pereira** [comment]
Try again please

**Comment by puyt** [comment]
How would you like to merge the npm package?

**Comment by dubisdev** [comment]
Hi @puyt 

We are working on automatic releases to npm. The idea is using a GH action to do this.

Once we have implemented the CI (and if you agree with it) we can publish this under our scope using our token. The package name would be `@cerebroapp/cerebro-snippets`.

To avoid duplicates then, we would need you to deprecate the old package.
